============================= test session starts =============================
platform win32 -- Python 3.10.16, pytest-8.4.0, pluggy-1.6.0 -- C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\Vassoura
configfile: pyproject.toml
plugins: anyio-4.9.0
collecting ... collected 7 items

vassoura/tests/test_heuristics.py::test_iv_low_iv_removed PASSED         [ 14%]
vassoura/tests/test_heuristics.py::test_variance_filters_const_and_dominant PASSED [ 28%]
vassoura/tests/test_heuristics.py::test_graph_cut_removes_one_of_highly_correlated_pair PASSED [ 42%]
vassoura/tests/test_heuristics.py::test_ks_separation_filters_low_separation PASSED [ 57%]
vassoura/tests/test_heuristics.py::test_psi_stability_detects_drift PASSED [ 71%]
vassoura/tests/test_heuristics.py::test_partial_corr_cluster_removes_in_correlated_block PASSED [ 85%]
vassoura/tests/test_heuristics.py::test_all_artefacts_present PASSED     [100%]

============================== warnings summary ===============================
vassoura/tests/test_heuristics.py::test_psi_stability_detects_drift
  C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
    result = getattr(ufunc, method)(*inputs, **kwargs)

vassoura/tests/test_heuristics.py::test_all_artefacts_present
  C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\Vassoura\vassoura\heuristics.py:896: RuntimeWarning: invalid value encountered in sqrt
    pcorr = -prec / np.sqrt(np.outer(np.diag(prec), np.diag(prec)))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 7 passed, 2 warnings in 3.01s ========================
