============================= test session starts =============================
platform win32 -- Python 3.10.16, pytest-8.4.0, pluggy-1.6.0 -- C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\Vassoura
configfile: pyproject.toml
plugins: anyio-4.9.0
collecting ... collected 5 items

vassoura/tests/test_session.py::test_corr_removal PASSED                 [ 20%]
vassoura/tests/test_session.py::test_vif_removal PASSED                  [ 40%]
vassoura/tests/test_session.py::test_iv_removal FAILED                   [ 60%]
vassoura/tests/test_session.py::test_manual_removal PASSED               [ 80%]
vassoura/tests/test_session.py::test_reset PASSED                        [100%]

================================== FAILURES ===================================
_______________________________ test_iv_removal _______________________________

df_toy =            a         b         c  d
0   0.496714  0.399939  0.448327  0
1  -0.138264 -0.101233 -0.119749  1
2   0.6476...  0.231680  0.246368  1
98  0.005113 -0.202142 -0.098514  0
99 -0.234587 -0.220040 -0.227314  1

[100 rows x 4 columns]

    def test_iv_removal(df_toy):
        vs = Vassoura(df_toy, target_col="d", heuristics=["iv"], thresholds={"iv": 0.0001})
        df_clean = vs.run()
>       assert "iv<" in vs.history[-1]["reason"] or len(vs.dropped) == 0
E       IndexError: list index out of range

vassoura\tests\test_session.py:39: IndexError
---------------------------- Captured stdout call -----------------------------
[Vassoura] IV heuristic (thr<0.0001) � removendo low IV
---------------------------- Captured stderr call -----------------------------
INFO | a -> num�rica
INFO | b -> num�rica
INFO | c -> num�rica
INFO | M�todo de correla��o sugerido: pearson
INFO | Matriz de correla��o pearson calculada para 3 vari�veis num�ricas
INFO | a -> num�rica
INFO | b -> num�rica
INFO | c -> num�rica
INFO | VIF calculado para 3 vari�veis
------------------------------ Captured log call ------------------------------
INFO     vassoura:utils.py:144 a -> num�rica
INFO     vassoura:utils.py:144 b -> num�rica
INFO     vassoura:utils.py:144 c -> num�rica
INFO     vassoura:correlacao.py:129 M�todo de correla��o sugerido: pearson
INFO     vassoura:correlacao.py:151 Matriz de correla��o pearson calculada para 3 vari�veis num�ricas
INFO     vassoura:utils.py:144 a -> num�rica
INFO     vassoura:utils.py:144 b -> num�rica
INFO     vassoura:utils.py:144 c -> num�rica
INFO     vassoura:vif.py:150 VIF calculado para 3 vari�veis
============================== warnings summary ===============================
vassoura/tests/test_session.py::test_vif_removal
vassoura/tests/test_session.py::test_iv_removal
  C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
    vif = 1. / (1. - r_squared_i)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED vassoura/tests/test_session.py::test_iv_removal - IndexError: list index out of range
=================== 1 failed, 4 passed, 2 warnings in 2.44s ===================
